/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blive_agora_VideoPreProcessing */

#ifndef _Included_com_blive_agora_VideoPreProcessing
#define _Included_com_blive_agora_VideoPreProcessing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blive_agora__VideoPreProcessing
 * Method:    enablePreProcessing
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_blive_agora_VideoPreProcessing_enablePreProcessing
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
